version: '3.8'

services:
  c-compiler:
    build: .
    container_name: c-compiler-container
    volumes:
      - ./src:/app/src
    command: ./hello
    ports:
      - "8080:80"  # Optional: Only if you want to expose any ports for communication (not needed in your case)
